services:
  finance-pro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-pro
    ports:
      - "80:80"
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: finance-pro-tunnel
    command:
      - "http"
      - "finance-pro:80"
      - "--domain=wince-freckled-tribunal.ngrok-free.dev"
    environment:
      - NGROK_AUTHTOKEN=3EicKyiFGrhFl7T7HDP3rhtYg1W_do1fqpYHgag4miyQ39ou
    depends_on:
      - finance-pro
    restart: always
